import type { ExchangeAdapterSlug } from "@/lib/exchanges/types";

export const EXCHANGE_LABELS: Record<ExchangeAdapterSlug, string> = {
  gate: "Gate",
  bitget: "Bitget",
  bingx: "BingX",
  mexc: "MEXC",
  bybit: "Bybit",
  okx: "OKX",
  kucoin: "KuCoin",
  lbank: "LBank",
  xt: "XT",
  binance: "Binance",
  htx: "HTX",
  kraken: "Kraken",
  bitmart: "BitMart",
  toobit: "Toobit",
  coinw: "CoinW",
  ourbit: "Ourbit",
  zoomex: "Zoomex",
  coinex: "CoinEx",
  phemex: "Phemex",
  bitunix: "Bitunix",
  whitebit: "WhiteBIT",
  tapbit: "Tapbit",
  ascendex: "AscendEX",
  bitrue: "Bitrue",
  blofin: "BloFin",
  woox: "WOO X",
  asterdex: "Aster",
  hyperliquid: "Hyperliquid",
};
